const model = {
    inputsView: '',
    visHandlekurv: false,
    handlekurv: '',
    htmlForHandlekurv : 'none',
    Totalpris: 0,
    disker: [
        {
            id:1,
            antall: 0,
            navn: "Paul Mcbeth Buzz First run",
            type: "buzz",
            merke: "Discraft",
            mold: "Esp",
            år: 2020,
            farge: ["orange", "rød", "blå"],
            vekt: ["172", "173", "175"],
            pris: 299,
            img: "bilder/bilde4.jpg",
            påLager: 2,
        },
        {
            id:2,
            antall: 0,
            navn: "Signert Jeremy Koling",
            type: "Thunderbird",
            merke: "innova",
            mold: "star",
            år: 2019,
            farge: ["hvit", "rød", "blå"],
            vekt: ["172", "173", "175"],
            pris: 299,
            signatur: "Bla Bla",
            påLager: 2,
            img: "bilder/bilde1.jpg",
        },
        {
            id:3,
            antall: 0,
            navn: "Signert Jeremy Koling",
            type: "Thunderbird", 
            merke: "innova",
            mold: "star",
            år: 2019,
            farge: ["hvit", "rød", "blå"],
            vekt: ["172", "173", "175"],
            pris: 299,
            påLager: 2,
            img: "bilder/bilde2.jpg",
        },
        {
            id:4,
            antall: 0,            
            navn: "Paul Mcbeth Supremeflight",
            type: "Firebird",
            merke: "innova",
            mold: "star",
            år: 2018,
            farge: ["gul", "rød", "blå"],
            vekt: ["172", "173", "175"],
            pris: 299, 
            påLager: 1,
            img: "bilder/bilde3.jpg",
        },
        
    

    ],

     

};